### ISSUE TITLE
bildquellen

### ISSUE THREAD

**Issue by allen-ziegenfus** [allen-ziegenfus/demokratie.github.io#28]

**Comment by allen-ziegenfus** [comment]
@riedbox  sieht das ok aus?

![image](https://user-images.githubusercontent.com/16581685/124220736-f8a56980-dac3-11eb-89d5-f09280be8fae.png)
https://allen-ziegenfus.github.io/demokratie.github.io/personen/konrad-arndt/lang.html

**Comment by riedbox** [comment]
Lieber Allen,

Sieht super aus und verlinkt ist es auch noch. Prima, danke.

Wie das mit der Lupenfunktion bei der digitalen Sammlung vom Städel funktioniert, weiß ich auch nicht. Gibt es Im Quellcode  der Seite vielleicht einen Hinweis?

Herzliche Grüße
Horst

riedbox media

Horst Ziegenfusz
Veilchenweg 7
D-64546 Mörfelden-Walldorf
Fon: ++49 6105 454712
Mobil: ++ 49 172 69 33 003
***@***.***

**Comment by riedbox** [comment]
Lieber Allen,

habe gerade gesehen, dass auf allen Seiten am Ende „Herkunft der Bildquellen“ steht. Diesen Teil brauchen wir nur bei den Langversionen.

Kann man vielleicht Abb. 1 auch an den Anfang stellen?

Herzliche Grüße
Horst






riedbox media

Horst Ziegenfusz
Veilchenweg 7
D-64546 Mörfelden-Walldorf
Fon: ++49 6105 454712
Mobil: ++ 49 172 69 33 003
***@***.***

**Comment by allen-ziegenfus** [comment]
@riedbox  ok ich habe das jetzt gemacht.

https://allen-ziegenfus.github.io/demokratie.github.io/personen/konrad-arndt/lang.html
allerdings erfordert es eine anpassung, wie wir die bilder einfuegen:

https://github.com/allen-ziegenfus/demokratie.github.io/commit/3a40e0a40bfabcaf011582f418a33101fd06cd66

statt `{{ bild(bilder, 0) }}` sollten wir dann `{{ bild_einfuegen(bilder,'Abb 2.jpg')}}` verwenden

**Comment by riedbox** [comment]
Lieber Allen,

dachte ich mir schon. 

Vielen Dank für Deine Änderungen. 
Ist jetzt bei dem Bilderblock rechts eine Doppelung leider auch ohne Bildunterschrift.

Warten wir bei dieser Änderung erst mal meine Präsentation am Montag oder Dienstag ab.

Ich stelle Dir gleich noch zwei issues mit Entwürfen für die Projekt- und die Einführungsseiten auf GitHub ein.

Über WeTransfer sende ich Dir noch einmal die Webseiten mit den Flashanimationen zu. Vielleicht kannst Du mal schauen und mir eventuell einen Workflow dazu generieren. Das wäre super.


Herzliche Grüße

riedbox media

Horst Ziegenfusz
Veilchenweg 7
D-64546 Mörfelden-Walldorf
Fon: ++49 6105 454712
Mobil: ++ 49 172 69 33 003
***@***.***

**Comment by riedbox** [comment]
Zoom-Meeting beitreten
https://zoom.us/j/96016215906?pwd=d2x4OWoyVTMrbEFYN1c3R0cvS014Zz09

Meeting-ID: 960 1621 5906
Kenncode: 389627
Schnelleinwahl mobil
+12532158782,,96016215906#,,,,*389627# Vereinigte Staaten (Tacoma)
+13017158592,,96016215906#,,,,*389627# Vereinigte Staaten (Washington DC)

Einwahl nach aktuellem Standort
        +1 253 215 8782 Vereinigte Staaten (Tacoma)
        +1 301 715 8592 Vereinigte Staaten (Washington DC)
        +1 312 626 6799 Vereinigte Staaten (Chicago)
        +1 346 248 7799 Vereinigte Staaten (Houston)
        +1 669 900 6833 Vereinigte Staaten (San Jose)
        +1 929 436 2866 Vereinigte Staaten (New York)
Meeting-ID: 960 1621 5906
Kenncode: 389627
Ortseinwahl suchen: https://zoom.us/u/abgQrOaJpX




riedbox media

Horst Ziegenfusz
Veilchenweg 7
D-64546 Mörfelden-Walldorf
Fon: ++49 6105 454712
Mobil: ++ 49 172 69 33 003
***@***.***
