### ISSUE TITLE
Anpassung Projekt

### ISSUE THREAD

**Issue by riedbox** [allen-ziegenfus/demokratie.github.io#32]
Anbei der Entwurf für die Projektseite. Bitte Textblock auf den Satzspiegel wie bei den anderen Seiten setzten. 
Titel der Seite  (rechts)
Textüberschrift bitte größer machen (Zur Entstehungsgeschichte...)
![gestaltun_projekt](https://user-images.githubusercontent.com/50882487/124301600-57b8bc00-db60-11eb-8126-306715abe6ad.png)

**Comment by allen-ziegenfus** [comment]
![image](https://user-images.githubusercontent.com/16581685/124518279-a3ab7100-ddab-11eb-9aca-8bc12a764722.png)
