### ISSUE TITLE
Hauptbild Abb 1 umbenennen / Ordner "bilder" anlegen

### ISSUE THREAD

**Issue by riedbox** [allen-ziegenfus/demokratie.github.io#4]
Sollen die Abb 1 - Dateien in hauptbild umbenannt werden?

Ist es es OK die Bilder in einem Ordner "bilder" zu speichern

**Comment by allen-ziegenfus** [comment]
Abb 1 oder hauptbild geht beides, wir müssen uns einfach festlegen.

meinst du ein "bilder" Ordner pro Person? das ist kein Problem. Ich will nur dass die Zuordnung Bild - Person nicht verloren geht.

**Comment by riedbox** [comment]
Hallo Allen, schau Mal. Habe alles hochgeladen in arc.

**Comment by riedbox** [comment]
Hallo Allen,

meinte natürlich den ordner /src.

Hier habe ich in Muse weiter am Dummy gearbeitet: https://fuer-demokratie-33-45-wiesbaden.de/prototyp/index.html

So sollte es aussehen. Vielleicht können wir uns am Wochenende noch einmal austauschen. Herzliche Grüße, Horst
